// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BulkDeleteDoneTodos() {
  return window['go']['main']['App']['BulkDeleteDoneTodos']();
}

export function CompleteTodo(arg1) {
  return window['go']['main']['App']['CompleteTodo'](arg1);
}

export function CreateRecurringTask(arg1) {
  return window['go']['main']['App']['CreateRecurringTask'](arg1);
}

export function CreateTodo(arg1) {
  return window['go']['main']['App']['CreateTodo'](arg1);
}

export function DeleteRecurringTask(arg1) {
  return window['go']['main']['App']['DeleteRecurringTask'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetNearOrOverdueMemos() {
  return window['go']['main']['App']['GetNearOrOverdueMemos']();
}

export function GetRecurringPanel() {
  return window['go']['main']['App']['GetRecurringPanel']();
}

export function GetRecurringTask(arg1) {
  return window['go']['main']['App']['GetRecurringTask'](arg1);
}

export function GetRecurringTasks() {
  return window['go']['main']['App']['GetRecurringTasks']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTodo(arg1) {
  return window['go']['main']['App']['GetTodo'](arg1);
}

export function GetTodos(arg1) {
  return window['go']['main']['App']['GetTodos'](arg1);
}

export function OpenLocalPath(arg1) {
  return window['go']['main']['App']['OpenLocalPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReorderTodos(arg1) {
  return window['go']['main']['App']['ReorderTodos'](arg1);
}

export function RestoreTodo(arg1) {
  return window['go']['main']['App']['RestoreTodo'](arg1);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SnoozeReminder(arg1, arg2) {
  return window['go']['main']['App']['SnoozeReminder'](arg1, arg2);
}

export function ToggleImportant(arg1) {
  return window['go']['main']['App']['ToggleImportant'](arg1);
}

export function ToggleRecurringTask(arg1) {
  return window['go']['main']['App']['ToggleRecurringTask'](arg1);
}

export function UpdateRecurringTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateRecurringTask'](arg1, arg2);
}

export function UpdateTodo(arg1, arg2) {
  return window['go']['main']['App']['UpdateTodo'](arg1, arg2);
}
